version: '3'

services:
  agent-1:
    image: jenkins/ssh-agent:alpine
    container_name: jenkins-agent-1
    networks:
    - jenkins-agents-network
    environment:
      JENKINS_AGENT_SSH_PUBKEY: 'ssh-rsa ...'
    expose:
    - 22:22

networks:
  jenkins-agents-network:
