version: '3'

services:
  agent-2:
    image: jenkins/ssh-agent:alpine
    container_name: jenkins-agent-2
    networks:
    - jenkins-agents-network
    environment:
      JENKINS_AGENT_SSH_PUBKEY: 'ssh-rsa ...'
    expose:
    - 22:22
  agent-3:
    image: jenkins/ssh-agent:alpine
    container_name: jenkins-agent-3
    networks:
    - jenkins-agents-network
    environment:
      JENKINS_AGENT_SSH_PUBKEY: 'ssh-rsa ...'
    expose:
    - 22:22


networks:
  jenkins-agents-network:
