name: Login to Docker Hub, build image and send to Docker Hub

on:
  - push
  - workflow_dispatch

env:
  DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKER_IMAGE_NAME: exadel-tasks


jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  

    - name: docker login
      run: |
        ls -laXh  || true
        pwd

    - name: Build the Docker image
      run: |
        docker build -t $DOCKER_USER/$DOCKER_IMAGE_NAME:latest ./Task4/Subtask4/
        docker tag $DOCKER_USER/$DOCKER_IMAGE_NAME:latest $DOCKER_USER/$DOCKER_IMAGE_NAME:${GITHUB_SHA::7}

    - name: Docker Push
      run: |
        docker push $DOCKER_USER/$DOCKER_IMAGE_NAME:latest
        docker push $DOCKER_USER/$DOCKER_IMAGE_NAME:${CI_COMMIT_SHA:0:8}
