name: "Extra task 1 - demo"

on: [push]

env:
  # DEPLOY_VER: $(git rev-parse --short HEAD)
  DEPLOY_VER0: $(git rev-parse --short=4 ${{ github.sha }})
  DEPLOY_VER1: ${{ github.sha }}
  DEPLOY_VER2: ${{ $GITHUB_SHA }}
  DEPLOY_VER3: ${ $GITHUB_SHA }
  DEPLOY_VER4: ${$GITHUB_SHA}

  DEPLOY_VER5: ${$GITHUB_SHA}
  DEPLOY_VER6: ${{ github.sha }}
  YEAR: 2018


jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - run: ls -laXh .
    - run: cat ./log.txt
    - run: echo "Hello from $DEPLOY_VER commit"
    - run: echo "Hello from $GITHUB_SHA commit"
