name: "Extra task 1 - demo"

on: [push]

env:
  DEPLOY_VER: "${{ env.GITHUB_SHA }}"
  YEAR: 2018


jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - run: ls -laXh .
    - run: cat ./log.txt
    - run: echo "Hello from $DEPLOY_VER commit"
    - run: echo "Hello from $GITHUB_SHA commit"
