name: "Extra task 1 - demo"

on: [push]

env:
  DEPLOY_VER: ${{ github.sha }}
  YEAR: 2018

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
      with:
        ref: master

    - run: ls -laXh .
    - run: cat ./log.txt
    - run: echo "Hello from $DEPLOY_VER commit"


  job_2:
    runs-on: ubuntu-latest
    needs: job_1

    env:
      MONTH: 9
      DAY__OF_THE_MONTH: 8

    steps:
    - uses: actions/checkout@master
      with:
        ref: master

    - run: date
    - run: echo Day - $DAY__OF_THE_MONTH
    - run: echo Month - $MONTH
    - run: echo Year - $YEAR

    - run: echo Favorite day of week - ${{ secrets.FAVORITE_DAY_OF_WEEK }}
      if: ${{ secrets.FAVORITE_DAY_OF_WEEK }} == 6


