name: "Extra task 1 - demo"

on: [push]

env:
  DEPLOY_VER: $GITHUB_SHA
  YEAR: 2018

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - uses: musabeksadullaev/exadel-internship-2022-tasks@master
    - run: ls -laXh .
    - run: cat ./log.txt
    - run: echo "Hello from ${DEPLOY_VER} commit"
